baseURL = "http://adamkoziorz.github.io/"
languageCode = "en-us"
title = "Adam Koziorz"

[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[params.profileMode]
enabled = true
title = "Welcome!"
subtitle = "Adam Koziorz - Portfolio"
imageUrl = "hello.gif"
imageWidth = 200
imageHeight = 200
ShowBreadCrums = true

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/AdamKoziorz"

[[menu.main]]
identifier = "Courses Notes"
name = "Course Notes"
url = "/courses/"
weight = 1

[outputs]
home = [ "HTML", "RSS", "JSON" ]
