# Main Information
baseURL: http://adamkoziorz.github.io/
languageCode: en-us
title: Adam Koziorz
theme: PaperMod

# Toggles
enableInlineShortcodes: true
enableEmoji: true # allowing using emoji
ShowPostNavLinks: true
ShowBreadCrumbs: true

# Main Page (Parameters)
params:
    profileMode:
        enabled: true
        title: "Welcome!" # optional default will be site title
        subtitle: "Adam Koziorz - Portfolio"
        imageUrl: "hello.gif"
        imageWidth: 300 # custom size
        imageHeight: 300 # custom size
        buttons:
            - name: Github
              url: "https://github.com/AdamKoziorz"
            - name: Resume
              url: "https://adamkoziorz.github.io/resume.pdf"
        ShowBreadCrums: true

    env: production # to enable google analytics, opengraph, twitter-cards and schema.

    defaultTheme: light # defaultTheme: light or dark
    disableThemeToggle: false
    DateFormat: "2006-01-02"
    ShowShareButtons: false
    ShowReadingTime: false
    disableScrollToTop: false
    displayFullLangName: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: true
    ShowWordCounts: true
    VisitCount: true
    ShowLastMod: true
    ShowToc: true
    TocOpen: true
    comments: true


menu:
  main:
    - identifier: Courses Notes
      name: Course Notes
      url: courses
      weight: 1

# Other Stuff
outputs:
  home:
    - HTML
    - RSS
    - JSON

minify:
    disableXML: true
    # minifyOutput: true

permalinks:
    post: "/:title/"
    # post: "/:year/:month/:day/:title/"