# Main Information
baseURL: http://adamkoziorz.github.io/
languageCode: en-us
title: Adam Koziorz
theme: ["hugo-notice", "PaperMod"]

# Toggles
enableInlineShortcodes: true
enableEmoji: true # allowing using emoji
ShowPostNavLinks: true
ShowBreadCrumbs: true
builddrafts: true 
math: true
comments: true

# Allowing HTML code
markup:
  goldmark:
    renderer:
      unsafe: true


# Main Page (Parameters)
params:
    profileMode:
        enabled: true
        title: "Adam Koziorz" # optional default will be site title
        subtitle: 'HCI Student @ UWaterloo'
        imageUrl: "icon.png"
        imageWidth: 340 # custom size
        imageHeight: 340 # custom size
        buttons:
            - name: About Me
              url: /about
        ShowBreadCrums: true

    env: production # to enable google analytics, opengraph, twitter-cards and schema.

    defaultTheme: light # defaultTheme: light or dark
    disableThemeToggle: true
    # DateFormat: "January 2, 2006"
    ShowShareButtons: false
    ShowReadingTime: false
    disableScrollToTop: false
    displayFullLangName: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: true
    ShowWordCounts: true
    VisitCount: true
    ShowLastMod: true
    ShowToc: true
    TocOpen: false
    comments: true
    social: true


menu:
  main:
    - identifier: Focuses
      name: Areas of Focus
      url: areas-of-focus
      weight: 1

    - identifier: Blogs
      name: Blogs
      url: blogs
      weight: 2

    - identifier: Courses
      name: Courses
      url: courses
      weight: 3

# Other Stuff
outputs:
  home:
    - HTML
    - RSS
    - JSON

minify:
    disableXML: true
    # minifyOutput: true

permalinks:
    post: "/:title/"
    # post: "/:year/:month/:day/:title/"